const express = require("express");
const cors = require("cors");
const bcrypt = require("bcrypt");
const sqlite3 = require("sqlite3").verbose();

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.json());

// Database
const db = new sqlite3.Database("./users.db");

db.run(`
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT UNIQUE,
            password TEXT
            )
            `);

            // Register
            app.post("/register", async (req, res) => {
                try {
                        const { username, password } = req.body;

                                const hash = await bcrypt.hash(password, 10);

                                        db.run(
                                                    "INSERT INTO users(username,password) VALUES(?,?)",
                                                                [username, hash],
                                                                            function(err) {
                                                                                            if(err){
                                                                                                                return res.status(400).json({
                                                                                                                                        success:false,
                                                                                                                                                                message:"User exists"
                                                                                                                                                                                    });
                                                                                                                                                                                                    }

                                                                                                                                                                                                                    res.json({
                                                                                                                                                                                                                                        success:true,
                                                                                                                                                                                                                                                            message:"User created"
                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                    } catch(err){
                                                                                                                                                                                                                                                                                                            res.status(500).json({error:err.message});
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                // Login
                                                                                                                                                                                                                                                                                                                app.post("/login", (req, res) => {

                                                                                                                                                                                                                                                                                                                    const { username, password } = req.body;

                                                                                                                                                                                                                                                                                                                        db.get(
                                                                                                                                                                                                                                                                                                                                "SELECT * FROM users WHERE username=?",
                                                                                                                                                                                                                                                                                                                                        [username],
                                                                                                                                                                                                                                                                                                                                                async (err, user) => {

                                                                                                                                                                                                                                                                                                                                                            if(err || !user){
                                                                                                                                                                                                                                                                                                                                                                            return res.json({
                                                                                                                                                                                                                                                                                                                                                                                                success:false,
                                                                                                                                                                                                                                                                                                                                                                                                                    message:"Invalid username"
                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                            const match = await bcrypt.compare(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            password,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            user.password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if(match){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        success:true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message:"Login Successful"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            success:false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message:"Wrong password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(`Server running on port ${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });